/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --shadows M3.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useKeyboardControls } from "@react-three/drei";
import { Color, MathUtils } from "three";
import { useControls } from "leva";
import { useFrame } from "@react-three/fiber";

export function Car(props) {
  const { nodes, materials } = useGLTF("/M3.glb");
  const [, get] = useKeyboardControls();

  const leftLightRef = useRef(null);
  const rightLightRef = useRef(null);

  const backLightColors = useControls(
    "Back Light Color",
    {
      emissive: { value: new Color(0x740909), step: 0.01 },
      intensity: { value: 1, min: 0, max: 10, step: 0.01 },
    },
    {
      collapsed: true,
    }
  );

  materials["Material.004"].emissive = new Color(0x740909);
  materials["Material.004"].emissiveIntensity = 2;
  materials["Material.006"].emissive = new Color(0x740909);
  materials["Material.006"].emissiveIntensity = 0;
  materials["Material.002"].emissiveIntensity = 20;
  materials['Material.002'].emissive = new Color(0xffc562);
  let intensity = 1;
  useFrame(() => {
    const { brake } = get();
    materials["Material.006"].emissiveIntensity = MathUtils.lerp(
      materials["Material.006"].emissiveIntensity,
      brake ? 1200 : 3,
      0.1
    );

    intensity = MathUtils.lerp(
      leftLightRef.current.intensity,
      brake ? 4 : 1,
      0.1
    );
    leftLightRef.current.intensity = intensity;
    rightLightRef.current.intensity = intensity;
  });

  return (
    <group
      {...props}
      dispose={null}
      rotation={[0, -Math.PI / 2, 0]}
      scale={0.9}
      position={[-0.8, -0.48, 0]}
    >
      <pointLight
        ref={leftLightRef}
        position={[0.35, 0.48, -2.8]}
        intensity={1}
        color="#740909"
      />
      <pointLight
        ref={rightLightRef}
        position={[-0.35, 0.48, -2.8]}
        intensity={1}
        color="#740909"
      />

      <group position={[-0.006, 0.611, 0.573]} scale={0.055}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_64.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_65.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_66.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_67.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <group position={[-0.006, 0.611, 0.573]} scale={0.055}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_69.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_70.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_72.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <group position={[0, 0, -0.011]} scale={0.328} />
      <group position={[0, 0, -1.94]} scale={0.328}>
        <group position={[-1.583, 0.712, 0.663]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_55.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_55_1.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_55_2.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_55_3.geometry}
            material={materials["Material.002"]}
          />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.031}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_84.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_85.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group position={[0.243, 0.611, 2.652]} scale={0.055}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_89.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_90.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_91.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_92.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <group
        position={[-0.006, 0.247, -1.723]}
        rotation={[0, 0, Math.PI / 2]}
        scale={0.265}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_108.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_109.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_110.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_111.geometry}
          material={materials["Material.004"]}
        />{" "}
        // brakes
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_112.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_113.geometry}
          material={materials["Material.006"]}
        />{" "}
        //backlit
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_114.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_115.geometry}
          material={materials["Material.014"]}
        />
      </group>
      <group position={[0, 0.473, -0.751]} scale={[0.16, 0.225, 0.078]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_96.geometry}
          material={materials["Material.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_97.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <group position={[0, 0.774, 0.995]} scale={0.161}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_101.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_102.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_62.geometry}
        material={materials["Material.008"]}
        position={[-0.006, 0.605, 0.573]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_87.geometry}
        material={materials["Material.003"]}
        position={[0.317, 0.524, -0.235]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.076}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_94.geometry}
        material={materials["Material.003"]}
        position={[-0.057, 0.375, -0.417]}
        rotation={[0, -0.048, 0]}
        scale={-0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_99.geometry}
        material={materials["Material.014"]}
        position={[0, 0.473, -1.276]}
        scale={[0.16, 0.225, 0.078]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_104.geometry}
        material={materials["Material.008"]}
        position={[0, 0.503, 0.676]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 0.91]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_106.geometry}
        material={materials["Material.003"]}
        position={[0.243, 0.622, -0.4]}
      />
    </group>
  );
}

useGLTF.preload("/M3.glb");
